### ISSUE TITLE
installing requirements

### ISSUE THREAD

**Issue by Kashish121** [SmartPracticeschool/SBSPS-Challenge-2700-Twitter-Sentiment-Analysis-Extraction-for-COVID-19#14]
Hi, 

I have an issue while installing the requirements for the repository.

![image](https://user-images.githubusercontent.com/56366103/152847462-356164e1-9697-46a8-8b2f-3dc67b2f5f3c.png)

Python version - 3.10.2
pip version - 22.0.3

How do I tackle this issue?

**Comment by Kashish121** [comment]
Hi,
Here's an error while installing requirements,
```
Failed to build Bottleneck
ERROR: Could not build wheels for Bottleneck, which is required to install pyproject.toml-based projects
```
Although bottleneck was already installed,

```
Collecting Bottleneck==1.3.2
  Using cached Bottleneck-1.3.2.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```

ps. I had to change versions of a few packages and for compatibility.

**Comment by Nik-V9** [comment]
Please refer to the following page: https://stackoverflow.com/questions/60198432/failed-building-wheel-for-bottleneck-error

I believe the error is being caused due to a compatibility issue with Windows and PyPI. I would recommend using conda.

**Comment by Kashish121** [comment]
Thanks for your help :)
